### PR TITLE
Fix for #20

### PR DESCRIPTION
**Pull request by fscheiner**
* also changed version scheme to semver (see https://semver.org/)
* also fixed GHA build badge

### CODE REVIEW

**Review by msalle — APPROVED** [review]
Hi Frank,
looks good to me, I see no reason not to merge!
One remark, we might want to make a 'reminder' issuer since there are a few more changes between `_f_readdir_nlst` and `_f_readdir_mlsd` that seem to be not entirely trivial.
- For example the `for` loop has an additional check `rec && rec < eol` vs simply `rec < eol`. I think the longer check is probably also the right one in the other case, but I haven't looked in detail.
- Also `strstr(rec, "\r\n");` vs `strstr(rec, "\n");` Not sure which is the right one but I'd expect they should be the same?
And there are other differences.

But in any case, your fix is AFAICT the right one and therefore go for it!

**Comment by fscheiner** [comment]
@msalle 
> Hi Frank, looks good to me, I see no reason not to merge! One remark, we might want to make a 'reminder' issuer since there are a few more changes between `_f_readdir_nlst` and `_f_readdir_mlsd` that seem to be not entirely trivial.

Indeed, I noticed those, too, but didn't want to change too much at once w/o a further read in the RFCs.

> * For example the `for` loop has an additional check `rec && rec < eol` vs simply `rec < eol`. I think the longer check is probably also the right one in the other case, but I haven't looked in detail.

In the "old" code it was about like it is in `_f_readdir_nlst()` now:
```
for (rec = listing; ec == EC_SUCCESS && rec && *rec; rec = eor + 2)
```
...but I think we can do without the check that `rec` is not `NULL`, because if the program flow breaks out of the `while` loop before `listing` becomes not `NULL`, it goes to `cleanup:` directly afterwards:

https://github.com/gridcf/UberFTP/blob/c687176a0707b83cc3693c42c42a6e847f87e63a/ftp.c#L4024-L4040

> * Also `strstr(rec, "\r\n");` vs `strstr(rec, "\n");` Not sure which is the right one but I'd expect they should be the same?
>       And there are other differences.

This might well be because of differences in what FTP servers return for `MLSD` and `NLST`.  According to [RFC 959](https://datatracker.ietf.org/doc/html/rfc959#page-33) for the response to `NLST`:

> [...] The data will be transferred in ASCII or EBCDIC type over the data connection as valid pathname strings separated by `<CRLF>` or `<NL>`. [...]

...so checking for just `\n` will work for different server implementations. For the response to `MLSD` I only see `<CRLF>` as separator in [RFC 3659](https://datatracker.ietf.org/doc/html/rfc3659#page-24), so this seems to be correct as is.

> But in any case, your fix is AFAICT the right one and therefore go for it!

That's what I wanna hear! :-) We can continue the discussion here I think, even after the PR was merged.

**Comment by msalle** [comment]
> In the "old" code it was about like it is in `_f_readdir_nlst()` now:
> 
> ```
> for (rec = listing; ec == EC_SUCCESS && rec && *rec; rec = eor + 2)
> ```
> 
> ...but I think we can do without the check that `rec` is not `NULL`, because if the program flow breaks out of the `while` loop before `listing` becomes not `NULL`, it goes to `cleanup:` directly afterwards:

there are actually some issues with the underlying `Strncat()` and `Strndup()` (and possibly others) as defined in misc.c: the latter is doing a `memcpy()` while the `src` could potentially be NULL and the former is calling this `Strndup()` without checking that src isn't also NULL inside the `if (dst == NULL)`. Also `Strncat()` is calling `realloc()` without checking the return value isn't NULL. Other functions in misc.c seem to have similar issues with calling malloc and friends without checking the return value. We definitely need to cleanup this code at some point.

> > * Also `strstr(rec, "\r\n");` vs `strstr(rec, "\n");` Not sure which is the right one but I'd expect they should be the same?
> >   And there are other differences.
> 
> This might well be because of differences in what FTP servers return for `MLSD` and `NLST`. According to [RFC 959](https://datatracker.ietf.org/doc/html/rfc959#page-33) for the response to `NLST`:
> 
> > [...] The data will be transferred in ASCII or EBCDIC type over the data connection as valid pathname strings separated by `<CRLF>` or `<NL>`. [...]
> 
> ...so checking for just `\n` will work for different server implementations. For the response to `MLSD` I only see `<CRLF>` as separator in [RFC 3659](https://datatracker.ietf.org/doc/html/rfc3659#page-24), so this seems to be correct as is.

ok, that indeed sounds fine probably.
Not sure if this windows safe though: AFAIK Windows still uses the single symbolic "\n" for <CR><LF> if a file is opened as text? That was always the famous difference between opening a file as text vs binary (`fopen(..., "rb")`). See https://stackoverflow.com/a/2174899

> 
> > But in any case, your fix is AFAICT the right one and therefore go for it!
> 
> That's what I wanna hear! :-) We can continue the discussion here I think, even after the PR was merged.

**Comment by fscheiner** [comment]
@msalle 
> there are actually some issues with the underlying `Strncat()` and `Strndup()` (and possibly others) as defined in misc.c: the latter is doing a `memcpy()` while the `src` could potentially be NULL and the former is calling this `Strndup()` without checking that src isn't also NULL inside the `if (dst == NULL)`. Also `Strncat()` is calling `realloc()` without checking the return value isn't NULL. Other functions in misc.c seem to have similar issues with calling malloc and friends without checking the return value. We definitely need to cleanup this code at some point.

Agreed. We should look into that (plus the issue with the `cat` functionality in UberFTP) and I welcome your patches! ;-)
UPDATE: I created #22 and a possible "fix" for it.

> > > * Also `strstr(rec, "\r\n");` vs `strstr(rec, "\n");` Not sure which is the right one but I'd expect they should be the same?
> > >   And there are other differences.
> > 
> > 
> > This might well be because of differences in what FTP servers return for `MLSD` and `NLST`. According to [RFC 959](https://datatracker.ietf.org/doc/html/rfc959#page-33) for the response to `NLST`:
> > > [...] The data will be transferred in ASCII or EBCDIC type over the data connection as valid pathname strings separated by `<CRLF>` or `<NL>`. [...]
> > 
> > 
> > ...so checking for just `\n` will work for different server implementations. For the response to `MLSD` I only see `<CRLF>` as separator in [RFC 3659](https://datatracker.ietf.org/doc/html/rfc3659#page-24), so this seems to be correct as is.
> 
> ok, that indeed sounds fine probably. Not sure if this windows safe though: AFAIK Windows still uses the single symbolic "\n" for if a file is opened as text?

Really? I always thought, UNIX text is displayed without line endings in the Windows Notepad editor, because UNIX text is using *only* `\n` as line endings, whereas DOS/Windows is using `<CR><LF>` instead.

> That was always the famous difference between opening a file as text vs binary (`fopen(..., "rb")`). See https://stackoverflow.com/a/2174899

I had to look that up and checking `fopen(3)` tells, that this (i.e. an extra `b` in the `mode` argument) "_is ignored on all POSIX conforming systems, including Linux_". And I am not aware of any Windows version of UberFTP.

Anyhow, I don't think this is relevant here, because this is about directory/pathname listings over an (Grid)FTP data channel not file contents.

**Comment by msalle** [comment]
> @msalle
> 
> > there are actually some issues with the underlying `Strncat()` and `Strndup()` (and possibly others) as defined in misc.c: the latter is doing a `memcpy()` while the `src` could potentially be NULL and the former is calling this `Strndup()` without checking that src isn't also NULL inside the `if (dst == NULL)`. Also `Strncat()` is calling `realloc()` without checking the return value isn't NULL. Other functions in misc.c seem to have similar issues with calling malloc and friends without checking the return value. We definitely need to cleanup this code at some point.
> 
> Agreed. We should look into that (plus the issue with the `cat` functionality in UberFTP) and I welcome your patches! ;-)   UPDATE: I created #22 and a possible "fix" for it.

Great! I'll  have a look later!

> > > > * Also `strstr(rec, "\r\n");` vs `strstr(rec, "\n");` Not sure which is the right one but I'd expect they should be the same?
> > > >   And there are other differences.
> > > 
> > > 
> > > This might well be because of differences in what FTP servers return for `MLSD` and `NLST`. According to [RFC 959](https://datatracker.ietf.org/doc/html/rfc959#page-33) for the response to `NLST`:
> > > > [...] The data will be transferred in ASCII or EBCDIC type over the data connection as valid pathname strings separated by `<CRLF>` or `<NL>`. [...]
> > > 
> > > 
> > > ...so checking for just `\n` will work for different server implementations. For the response to `MLSD` I only see `<CRLF>` as separator in [RFC 3659](https://datatracker.ietf.org/doc/html/rfc3659#page-24), so this seems to be correct as is.
> > 
> > 
> > ok, that indeed sounds fine probably. Not sure if this windows safe though: AFAIK Windows still uses the single symbolic "\n" for if a file is opened as text?
> 
> Really? I always thought, UNIX text is displayed without line endings in the Windows Notepad editor, because UNIX text is using _only_ `\n` as line endings, whereas DOS/Windows is using `<CR><LF>` instead.

Sorry, I wasn't clear. I mean if you use `\n` on windows in a file opened as text file, i.e. not binary, it translates into `<CR><LF>`.

> > That was always the famous difference between opening a file as text vs binary (`fopen(..., "rb")`). See https://stackoverflow.com/a/2174899
> 
> I had to look that up and checking `fopen(3)` tells, that this (i.e. an extra `b` in the `mode` argument) "_is ignored on all POSIX conforming systems, including Linux_". And I am not aware of any Windows version of UberFTP.

probably not no, it was more of a generic remark, and we can probably ignore it (-;
And indeed it's ignored on POSIX systems since they use the single `<LF>` characters (in former days Mac used only `<CR>` and Commodore64 used `<LF><CR>`  and then you have all different combinations...)

> 
> Anyhow, I don't think this is relevant here, because this is about directory/pathname listings over an (Grid)FTP data channel not file contents.

true, I was more a bit surprised about the different and mixed usage of both.

**Comment by fscheiner** [comment]
@msalle:
> > > That was always the famous difference between opening a file as text vs binary (`fopen(..., "rb")`). See https://stackoverflow.com/a/2174899
> > 
> > 
> > I had to look that up and checking `fopen(3)` tells, that this (i.e. an extra `b` in the `mode` argument) "_is ignored on all POSIX conforming systems, including Linux_". And I am not aware of any Windows version of UberFTP.
> 
> probably not no, it was more of a generic remark, and we can probably ignore it (-; And indeed it's ignored on POSIX systems since they use the single `<LF>` characters (in former days Mac used only `<CR>` and Commodore64 used `<LF><CR>` and then you have all different combinations...)

Really? OMG! :-o

So a (Grid)FTP server on a C64 and older Macs (or Mac OSes) could give us problems in this regard. Surey nothing we can get fixed with a few `#ifdef`s... ;-)

> 
> > Anyhow, I don't think this is relevant here, because this is about directory/pathname listings over an (Grid)FTP data channel not file contents.
> 
> true, I was more a bit surprised about the different and mixed usage of both.

Me too actually. I mean, every manufacturer of computers or operating systems should have the right to have its own line endings...

**Comment by fscheiner** [comment]
@msalle 
I'm adding some warnings from the recent builds of UberFTP 2.9.1 packages on the openSUSE Build Service which we should maybe address, too, in the future:

```
[   10s] make[1]: Entering directory '/home/abuild/rpmbuild/BUILD/uberftp-2.9.1'
[   10s] gcc -DHAVE_CONFIG_H -I.   -I/usr/include/globus -DOPENSSL_LOAD_CONF -I/usr/include/globus   -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -c cmds.c
[   10s] gcc -DHAVE_CONFIG_H -I.   -I/usr/include/globus -DOPENSSL_LOAD_CONF -I/usr/include/globus   -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -c filetree.c
[   10s] cmds.c: In function '_c_open':
[   10s] cmds.c:2209:14: warning: variable 'c' set but not used [-Wunused-but-set-variable]
[   10s]   int         c       = 0;
[   10s]               ^
[   10s] cmds.c: In function '_c_xfer_file':
[   10s] cmds.c:3373:18: warning: unused variable 'dmlp' [-Wunused-variable]
[   10s]   ml_t          * dmlp    = NULL;
[   10s]                   ^~~~
[   10s] cmds.c: In function '_c_open':
[   10s] cmds.c:2235:3: warning: ignoring return value of 'fgets', declared with attribute warn_unused_result [-Wunused-result]
[   10s]    fgets(pass, 128, stdin);
[   10s]    ^~~~~~~~~~~~~~~~~~~~~~~
[   11s] gcc -DHAVE_CONFIG_H -I.   -I/usr/include/globus -DOPENSSL_LOAD_CONF -I/usr/include/globus   -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -c logical.c
[   11s] gcc -DHAVE_CONFIG_H -I.   -I/usr/include/globus -DOPENSSL_LOAD_CONF -I/usr/include/globus   -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -c network.c
[   11s] gcc -DHAVE_CONFIG_H -I.   -I/usr/include/globus -DOPENSSL_LOAD_CONF -I/usr/include/globus   -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -c gsi.c
[   11s] gsi.c: In function 'gsi_dc_write':
[   11s] gsi.c:588:15: warning: variable 'ec' set but not used [-Wunused-but-set-variable]
[   11s]      errcode_t ec = EC_SUCCESS;
[   11s]                ^~
[   12s] gcc -DHAVE_CONFIG_H -I.   -I/usr/include/globus -DOPENSSL_LOAD_CONF -I/usr/include/globus   -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -c settings.c
[   12s] gcc -DHAVE_CONFIG_H -I.   -I/usr/include/globus -DOPENSSL_LOAD_CONF -I/usr/include/globus   -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -c ftp.c
[   12s] ftp.c: In function '_f_setup_pbsz':
[   12s] ftp.c:2926:2: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
[   12s]   if (F_CODE_SUCC(code));
[   12s]   ^~
[   12s] ftp.c:2927:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
[   12s]   {
[   12s]   ^
[   12s] ftp.c: In function '_f_parse_addrs':
[   12s] ftp.c:3403:19: warning: unused variable 'port' [-Wunused-variable]
[   12s]      int protocol, port;
[   12s]                    ^~~~
[   12s] gcc -DHAVE_CONFIG_H -I.   -I/usr/include/globus -DOPENSSL_LOAD_CONF -I/usr/include/globus   -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -c main.c
[   12s] main.c: In function '_m_parse_cmd_args':
[   12s] main.c:842:6: warning: variable 'ind' set but not used [-Wunused-but-set-variable]
[   12s]   int ind = 0;
[   12s]       ^~~
[   13s] gcc -DHAVE_CONFIG_H -I.   -I/usr/include/globus -DOPENSSL_LOAD_CONF -I/usr/include/globus   -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -c output.c
[   13s] gcc -DHAVE_CONFIG_H -I.   -I/usr/include/globus -DOPENSSL_LOAD_CONF -I/usr/include/globus   -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -c errcode.c
[   13s] gcc -DHAVE_CONFIG_H -I.   -I/usr/include/globus -DOPENSSL_LOAD_CONF -I/usr/include/globus   -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -c misc.c
[   14s] ftp.c: In function 'ftp_readdir':
[   14s] ftp.c:4208:16: warning: argument 1 null where non-null expected [-Wnonnull]
[   14s]     eor = rec + strlen(eor);
[   14s]                 ^~~~~~~~~~~
[   14s] In file included from /usr/include/globus/globus_common_include.h:88:0,
[   14s]                  from /usr/include/globus/globus_common.h:67,
[   14s]                  from linterface.h:49,
[   14s]                  from ftp.c:51:
[   14s] /usr/include/string.h:385:15: note: in a call to function 'strlen' declared here
[   14s]  extern size_t strlen (const char *__s)
[   14s]                ^~~~~~
[   14s] gcc -DHAVE_CONFIG_H -I.   -I/usr/include/globus -DOPENSSL_LOAD_CONF -I/usr/include/globus   -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -c unix.c
[   14s] gcc -DHAVE_CONFIG_H -I.   -I/usr/include/globus -DOPENSSL_LOAD_CONF -I/usr/include/globus   -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -c ftp_s.c
[   14s] unix.c: In function 'unix_readdir':
[   14s] unix.c:723:2: warning: 'readdir_r' is deprecated [-Wdeprecated-declarations]
[   14s]   while ((ret = readdir_r(dirp, entry, &result)) == 0 && result != NULL)
[   14s]   ^~~~~
[   14s] In file included from unix.c:48:0:
[   14s] /usr/include/dirent.h:183:12: note: declared here
[   14s]  extern int readdir_r (DIR *__restrict __dirp,
[   14s]             ^~~~~~~~~
[   14s] unix.c: In function '_unix_mlsx':
[   14s] unix.c:1078:9: warning: variable 'por' set but not used [-Wunused-but-set-variable]
[   14s]   int    por          = 0;
[   14s]          ^~~
[   14s] gcc -DHAVE_CONFIG_H -I.   -I/usr/include/globus -DOPENSSL_LOAD_CONF -I/usr/include/globus   -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -c radix.c
[   14s] radix.c: In function 'radix_encode':
[   14s] radix.c:77:32: warning: 'c' may be used uninitialized in this function [-Wmaybe-uninitialized]
[   14s]        (*outbuf)[j++] = radixN[c|((unsigned char) inbuf[i])>>4];
[   14s]                                ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   14s] gcc -DHAVE_CONFIG_H -I.   -I/usr/include/globus -DOPENSSL_LOAD_CONF -I/usr/include/globus   -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -c nc.c
[   14s] gcc -DHAVE_CONFIG_H -I.   -I/usr/include/globus -DOPENSSL_LOAD_CONF -I/usr/include/globus   -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -c ftp_a.c
[   15s] gcc -DHAVE_CONFIG_H -I.   -I/usr/include/globus -DOPENSSL_LOAD_CONF -I/usr/include/globus   -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -c ftp_eb.c
[   15s] gcc -DHAVE_CONFIG_H -I.   -I/usr/include/globus -DOPENSSL_LOAD_CONF -I/usr/include/globus   -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -c ml.c
[   15s] gcc -DHAVE_CONFIG_H -I.   -I/usr/include/globus -DOPENSSL_LOAD_CONF -I/usr/include/globus   -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -c cksum.c
[   15s] gcc -DHAVE_CONFIG_H -I.   -I/usr/include/globus -DOPENSSL_LOAD_CONF -I/usr/include/globus   -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -c perf.c
[   15s] gcc  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -lglobus_common -lglobus_gssapi_gsi  -o uberftp cmds.o filetree.o logical.o network.o gsi.o settings.o ftp.o main.o output.o errcode.o misc.o unix.o ftp_s.o radix.o nc.o ftp_a.o ftp_eb.o ml.o cksum.o perf.o  -lglobus_gssapi_gsi -lglobus_common 
[   15s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/uberftp-2.9.1'
```

**Comment by msalle** [comment]
Maybe make an issue of those warnings, then we can more easily keep track of them.
Some of them look like real bugs, such as line 2926 and 4208 in ftp.c, also 77 in radix.c

**Pull request merged**
