### PR TITLE
Make cat work correctly depending on env var

### LINKED ISSUE #22: "cat" prints out odd UNIX newline in UberFTP
UberFTP's `cat` functionality adds an UNIX newline to the output for both text and binary files in ASCII and binary transfer modes. This makes using the output in a pipeline - for example to hash its contents - at least irritating if you aren't aware of that. This is mostly relevant for non-interactive use.

### PR DESCRIPTION
**Pull request by fscheiner**
* If the env var UBERFTP_CAT_CORRECT is present, omit the odd UNIX newline
  that is printed out for non-empty files
* Fixes #22

### CODE REVIEW

**Review by msalle — CHANGES_REQUESTED** [review]
The changes in themselves look fine to me, but we also need to document this in the manpage (uberftp.1) I think.

**Comment by fscheiner** [comment]
> The changes in themselves look fine to me, but we also need to document this in the manpage (uberftp.1) I think.

Good point, thanks. I forgot about this when updating the other files. I'll update this PR accordingly.

**Comment by fscheiner** [comment]
@msalle:
I now also adapted the manpage and the help output of UberFTP. See changes for [uberftp.1](https://github.com/gridcf/UberFTP/pull/23/files#diff-c4739c36f8681b85e44fc290e8ff455d16cfe6626e6ac6b4f4911241beab52ba) and [main.c](https://github.com/gridcf/UberFTP/pull/23/files#diff-a0cb465674c1b01a07d361f25a0ef2b0214b7dfe9412b7777f89add956da10ec).

Another point: The UberFTP manpage states inside that it is actually from section `1c`, but when installed for example on CentOS 7 the UberFTP manpage is installed in section `1`:
```
[johndoe@gridftp-5 ~]$ apropos uberftp
uberftp (1)          - GridFTP-enabled client
```
I am not sure what section `1c` is for, but should we maybe not better change the section to `1` then, too?

**Comment by msalle** [comment]
> @msalle: I now also adapted the manpage and the help output of UberFTP. See changes for [uberftp.1](https://github.com/gridcf/UberFTP/pull/23/files#diff-c4739c36f8681b85e44fc290e8ff455d16cfe6626e6ac6b4f4911241beab52ba) and [main.c](https://github.com/gridcf/UberFTP/pull/23/files#diff-a0cb465674c1b01a07d361f25a0ef2b0214b7dfe9412b7777f89add956da10ec).

looks fine to me, thanks!

> Another point: The UberFTP manpage states inside that it is actually from section `1c`, but when installed for example on CentOS 7 the UberFTP manpage is installed in section `1`:
> 
> ```
> [johndoe@gridftp-5 ~]$ apropos uberftp
> uberftp (1)          - GridFTP-enabled client
> ```
> 
> I am not sure what section `1c` is for, but should we maybe not better change the section to `1` then, too?

I could only find an oracle page stating it is user commands. I think just 1 is probably much better. Also the file is already called `.1` not `.1c`.

**Comment by fscheiner** [comment]
> > Another point: The UberFTP manpage states inside that it is actually from section `1c`, but when installed for example on CentOS 7 the UberFTP manpage is installed in section `1`:
> > ```
> > [johndoe@gridftp-5 ~]$ apropos uberftp
> > uberftp (1)          - GridFTP-enabled client
> > ```
> > I am not sure what section `1c` is for, but should we maybe not better change the section to `1` then, too?
> 
> I could only find an oracle page stating it is user commands. I think just 1 is probably much better. Also the file is already called `.1` not `.1c`.

Exactly. I'll update things accordingly and force push the changes.

**Comment by fscheiner** [comment]
@msalle:
It's done. And detected a few other parts that needed changes on the way (see changes in [cmds.c](https://github.com/gridcf/UberFTP/pull/23/files#diff-b9e98103814691c65edae01f16f0efea82a853cff9b787cf9a52d956d27fe79d)).

**Review by msalle — APPROVED** [review]
Looks good, thanks!!

**Pull request merged**
