### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by fscheiner**
* Added short UberFTP description from manpage to README.md
* Updated URLs in `uberftp.1` and `mssftp.1`

### CODE REVIEW

**Review by msalle — CHANGES_REQUESTED** [review]
Not entirely sure we like to link to the very very old page which we can now only access via web.archive.org
It seems http://www.vonwelch.com/report/tcp_windows/ is newer (but please check).
Also, you have a Uber**f**TP which should be a UberFTP

**Comment by fscheiner** [comment]
> Not entirely sure we like to link to the very very old page which we can now only access via web.archive.org
> It seems http://www.vonwelch.com/report/tcp_windows/ is newer (but please check).

This one says:
```
[...]  It is out of date at this point, but I maintain it for historical reasons. A more recent reference document can be found at http://www.psc.edu/networking/projects/tcptune/
```
...but the referenced document is not available ATM. Ok, it seems to have been moved here:

http://www.psc.edu/tcp-tune

...but I find it's not a replacement for Von Welch's document but more of a supplement.

Not sure what to do, because readers might just try to jump to the referenced document and then get stuck as it's no longer there.

Maybe we link both Von Welch's "latest" version **and** the referenced document at the new location?

> Also, you have a Uber**f**TP which should be a UberFTP

~Thanks, will correct that.~ Done.

**Comment by msalle** [comment]
> ...but the referenced document is not available ATM. Ok, it seems to have been moved here:
> 
> http://www.psc.edu/tcp-tune
> 
> ...but I find it's not a replacement for Von Welch's document but more of a supplement.
> 
> Not sure what to do, because readers might just try to jump to the referenced document and then get stuck as it's no longer there.
> 
> Maybe we link both Von Welch's "latest" version **and** the referenced document at the new location?

I think they both have broken links (also the http://www.psc.edu/tcp-tune), so linking to both is probably indeed the best we can do.

**Comment by fscheiner** [comment]
> > [...]
> I think they both have broken links (also the http://www.psc.edu/tcp-tune), so linking to both is probably indeed the best we can do.

Ok, just force-pushed the corresponding update.

**Review by msalle — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
