### PR TITLE
Cleanup parsing of RFC2428 format responses

### LINKED ISSUE #11: Merge of devel introduced several potential SEGV
The merged commit https://github.com/gridcf/UberFTP/commit/1f28d62f2e688d0a4bfc89a754dfdf3424ef9ed7 introduces several potential SEGV situations.

Lines [3459-3473 in ftp.c](https://github.com/gridcf/UberFTP/blob/master/ftp.c#L3459-L3473) have several issues which can result in SEGV in case `strc` doesn't contain a '(', but is for example `"200 Passive delayed.\r\n"` (see below):
1. Around line 3464:
    - in line then sets `ptr` to point at the '\n'
    - line 3461 moves `ptr` to the '\0'
    - line 3463 `delim` becomes 0
    - line 3464 `ptr` is moved beyond the end of the string.
    - using then `ptr` in line 3471 can potentially result in a SEGV
1. Around lines 3471-3473:
    - If `delim` is 0, `strchr()` will typically return the position the terminating '\0' instead of NULL, see `man 3 strchr` under "RETURN VALUE". This means we never hit the `break` in 3471 but instead have `ptr` to point to that terminating '\0'
    - line 3473 then moves `ptr` beyond the end of the string
    - upon the next `strchr()` in the loop we can hit again a SEGV.
    - alternatively, since 1. already put `ptr` beyond the end, the `strchr()` with `delim==0` can get anywhere and `token[]` in line 3470 is filled with garbage from beyond the end of the string, resulting in random SEGV elsewhere.

This can be reproduced e.g. by enabling "passive delayed" mode from the client: After connection enter   
 `quote "OPTS PASV AllowDelayed=1"`
and do an `ls`. At that point the value of `strc` in [ftp.c line 3457](https://github.com/gridcf/UberFTP/blob/master/ftp.c#L3457) becomes `"200 Passive delayed.\r\n"`.

EDIT: changed lines selected in link from `#L3471-L3473` to `#L3459-L3473` (fscheiner)

### PR DESCRIPTION
**Pull request by msalle**
Several improvements and fixes in the RFC2428 format parsing code.
Among others prevent parsing the input string beyond the end (which caused
several potential SEGV).
Also add comments and cleanup the code structure for readability.

Fixes https://github.com/gridcf/UberFTP/issues/11

### CODE REVIEW

**Review by fscheiner — APPROVED** [review]
Looks good to me.

**Comment by msalle** [comment]
Hi @fscheiner just to check: did you manage to runtime test my patches? That would still be good...

**Comment by fscheiner** [comment]
No, not before merging it, I relied on your "testing" in gdb. But I will test the resulting `uberftp` with my IPv6 enabled GridFTP service.

**Comment by fscheiner** [comment]
@msalle 
Some results from testing `uberftp` with the patch from this PR:

* Using "delayed passive" for an `ls`:
```
## w/IPv6 (same for IPv4 but with different FQDN)
UberFTP (2.9 Beta)> open gridftp-5-ipv6.domain.tld
220 gridftp-5-ipv6.domain.tld GridFTP Server 13.20 (gcc64, 1566483868-0) [Grid Community Toolkit 6.2] ready.
230 User johndoe logged in.
UberFTP (2.9 Beta)> debug
Debug level set at 2 (ON)
UberFTP (2.9 Beta)> quote "OPTS PASV AllowDelayed=1"
---> Sending to gridftp-5-ipv6.domain.tld:
OPTS PASV AllowDelayed=1
200 OPTS Command Successful.
200 OPTS Command Successful.
UberFTP (2.9 Beta)> ls
---> Sending to gridftp-5-ipv6.domain.tld:
MODE S
200 Mode set to S.
---> Sending to gridftp-5-ipv6.domain.tld:
DCAU A
200 DCAU A.
---> Sending to gridftp-5-ipv6.domain.tld:
PBSZ 1135616
200 PBSZ=1135616
---> Sending to gridftp-5-ipv6.domain.tld:
PROT C
200 Protection level set to C.
---> Sending to gridftp-5-ipv6.domain.tld:
TYPE I
200 Type set to I.
---> Sending to gridftp-5-ipv6.domain.tld:
EPSV
200 Passive delayed.
No addresses found in EPSV response:
200 Passive delayed.
UberFTP (2.9 Beta)>
```
...so `uberftp` aborts the command after "processing" the `200 Passive delayed.` response to `EPSV` w/o trying to send a `LIST` command.

* Striped transfer: I actually don't know, how to initiate a striped transfer from within `uberftp` w/o using `[l]quote` commands - if at all possible - and these would actually bypass `uberftp`'s internal operation.

**Pull request merged**
